version: '2.1'

services:
  exercise:
    image: 'exercise:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercise
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    container_name: db
    image: postgres:9.6-alpine
    ports:
       - 5432:5432
    volumes:
       - /var/lib/postgresql/data
    healthcheck:
       test: psql --username postgres -c "SELECT COUNT(1) FROM pg_catalog.pg_roles;"
       interval: 30s
       timeout: 10s
       retries: 3
    environment:
       - SERVICE_NAME=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres